[package]
name = "eventsfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
input = "0.7"
libc = "0.2"
rodio = "0.16"
log = "0.4"
simple-logging = "2.0"
